apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: j-blog
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /*
spec:
  tls:
  - hosts:
    - jonasburster.de
    - www.katchblog.com
    secretName: katchblog-server-tls
  rules:
  - host: katchblog.com
    http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          serviceName: katchblog
          servicePort: 80
  - host: www.katchblog.com
    http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          serviceName: katchblog
          servicePort: 80